const Data = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque quis velit ac dapibus. Donec eu ex eget erat suscipit mollis. In congue auctor bibendum. ",
  "Sed semper erat magna, ut blandit lectus sollicitudin quis. Donec iaculis tristique ipsum et hendrerit. Vivamus id eros malesuada, iaculis sem vitae, tempus lacus. Donec placerat non neque consequat feugiat. Nullam sit amet malesuada augue. ",
  "Quisque dolor justo, mollis eget sagittis ut, tempus quis purus. Morbi et ante eget nisi consectetur placerat. In ultrices congue massa non sodales. Curabitur vehicula venenatis erat, vel dignissim elit. Aliquam justo nibh, suscipit nec fermentum sit amet, iaculis in tortor. Duis porta sapien eget posuere consectetur. ",
  "Integer aliquam maximus nulla, eu dictum nunc hendrerit eget. Nam lacus turpis, faucibus blandit elementum id, feugiat quis odio. Aenean fringilla mauris magna, vel consectetur quam tristique ac. Maecenas tempus ac neque vel semper.",
  "Curabitur consequat, lorem ac imperdiet tempor, ligula velit finibus leo, fermentum rhoncus orci odio quis arcu. Vivamus felis tortor, sollicitudin sed ullamcorper ac, tincidunt in mauris. Vestibulum aliquam augue nisl, et pharetra augue consequat sed. Quisque imperdiet non lacus a aliquam. In venenatis semper congue.",
  "Vivamus rhoncus pellentesque dapibus. Suspendisse velit mauris, dignissim vel cursus efficitur, commodo a arcu. Morbi dignissim, metus non maximus interdum, justo metus feugiat justo, sit amet condimentum mauris arcu eu ligula. Ut semper accumsan fermentum. Nunc maximus, lacus nec ullamcorper egestas, metus orci condimentum elit, eu luctus orci est sed tortor. Donec vel ultrices dui. Sed turpis sapien, efficitur non augue eget, tristique congue purus.",
  "Vestibulum ut molestie justo. Duis nunc augue, sollicitudin ac nisl consectetur, consectetur lobortis neque. Mauris vel mi augue. Sed tincidunt odio urna, vitae rutrum ligula gravida ac. Sed pulvinar ex id urna iaculis cursus. Praesent aliquam rutrum diam, id porta leo sollicitudin ac. Quisque in gravida dui.",
  "Nam mauris quam, consectetur vel lorem vitae, elementum vulputate sapien. Etiam eu diam vitae magna gravida malesuada sed et purus. Nullam vestibulum rhoncus velit. Praesent ante neque, gravida scelerisque ligula eget, vehicula mattis turpis. Vivamus et mauris orci. Vestibulum venenatis lectus eu felis dapibus pellentesque. Curabitur maximus libero vitae mi pulvinar, sit amet pharetra nisi tempor. Fusce porta nibh vel laoreet finibus. Donec pharetra, velit sed volutpat sagittis, leo tortor porta tortor, sed convallis eros orci a magna.",
  "Donec aliquet viverra quam, tincidunt suscipit mauris sollicitudin sit amet. Pellentesque suscipit ante neque, vel semper nunc sagittis eu. Integer vestibulum ultrices lectus, quis rutrum diam consectetur sed. In elementum magna vel erat mattis, ac iaculis odio suscipit. Nulla accumsan et nunc nec lacinia. Nam luctus risus lacus, vitae bibendum dolor laoreet nec. Cras scelerisque suscipit nisl quis tristique.",
  "Ut et augue tortor. Mauris sit amet felis risus. Curabitur consequat, lorem ac imperdiet tempor, ligula velit finibus leo, fermentum rhoncus orci odio quis arcu. Vivamus felis tortor, sollicitudin sed ullamcorper ac, tincidunt in mauris. Vestibulum aliquam augue nisl, et pharetra augue consequat sed. Quisque imperdiet non lacus a aliquam. In venenatis semper congue.",
];

export default Data;