const para = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit.Ut nec dapibus ante.Nam suscipit sed felis et vehicula.Integer at lacinia quam.Etiam eu varius justo, in volutpat turpis.Sed feugiat magna at metus bibendum, tempus tincidunt orci vulputate.Vivamus aliquet est vel lacinia elementum.Duis ornare metus quis est sagittis, nec eleifend urna luctus.Proin rhoncus magna leo, vitae facilisis urna blandit at.",

'Nulla ut risus sit amet quam accumsan semper nec ac augue.Nunc at enim sodales, molestie ex ut, viverra massa.Nulla malesuada luctus metus quis semper.Etiam diam ipsum, bibendum vitae interdum quis, rhoncus volutpat dui.Nullam eu laoreet justo.Nulla elit neque, sollicitudin sit amet augue vitae, ultrices fringilla nibh.Aliquam ac tortor mattis, tempor nisi ut, rhoncus velit.Nam facilisis urna vitae justo bibendum sodales.Nunc tristique interdum porta.Maecenas erat lorem, pulvinar id blandit et, egestas id sapien.Donec consectetur non mi eget maximus.Morbi semper orci eget congue pharetra.Sed rhoncus efficitur varius.Praesent varius rutrum dui vel iaculis.Nam dignissim imperdiet diam, vitae bibendum lectus vestibulum quis.',

'Vivamus vitae vulputate enim.Vestibulum sagittis, ligula tempor placerat commodo, lorem ipsum hendrerit orci, vitae commodo lectus justo nec quam.Nam lorem mauris, pretium eget dui nec, tempus commodo metus.Mauris vulputate non sem vitae viverra.Duis tristique eu leo a finibus.Cras commodo dictum sollicitudin.Duis id sapien et nulla mollis pellentesque in fermentum justo.Morbi nec viverra urna.Proin convallis libero erat, elementum pretium augue lacinia a.',

'Maecenas in accumsan velit.Vivamus eu finibus orci, sit amet laoreet elit.Nulla purus felis, dignissim nec congue sit amet, maximus ac tellus.Aliquam ultrices id dui at ullamcorper.Proin tortor nibh, consectetur eu euismod et, laoreet ut magna.Praesent tristique aliquam hendrerit.Nullam id tempus leo.Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Morbi dignissim mi dui, ac ultricies ipsum bibendum vel.Fusce consequat, erat vel lobortis suscipit, nibh quam convallis leo, at venenatis turpis lacus at felis.Cras libero ipsum, sagittis ut lacus a, faucibus tristique augue.',

'Ut sit amet fermentum metus, sit amet malesuada mi.Suspendisse id pretium mauris.Etiam placerat, sapien vel facilisis fermentum, turpis mi euismod libero, vitae interdum ipsum arcu eu tellus.Maecenas feugiat tincidunt mollis.Integer sapien dui, ullamcorper quis vestibulum eget, varius ac orci.Praesent vehicula, orci sit amet consectetur scelerisque, nibh nibh pretium ipsum, nec consectetur urna ante ac nisi.Proin augue nibh, ornare a congue at, tincidunt vitae dolor.Phasellus pulvinar ipsum vitae lacus ornare ultrices.Donec sodales lectus vitae arcu iaculis tempus.Suspendisse volutpat nulla eget nulla interdum maximus.Sed iaculis finibus quam quis tincidunt.Pellentesque diam ipsum, tempus a eleifend eu, interdum ut odio.Duis mi velit, semper et tempus vitae, finibus eu odio.Donec odio neque, aliquam a tortor eget, pretium volutpat sem.',

'Duis sed tempus tortor.Morbi sit amet odio id ipsum condimentum hendrerit vitae at odio.Quisque ut risus vehicula, efficitur tortor a, tempus metus.Maecenas ut pharetra turpis, quis tempor ipsum.Etiam lobortis congue risus nec tempor.Sed vel lorem odio.Fusce sodales laoreet eros, sit amet finibus risus.Vivamus ornare ac nunc id facilisis.In hac habitasse platea dictumst.Sed interdum, magna sed suscipit auctor, erat neque vulputate odio, in interdum diam lorem sed massa.',

'Nunc lobortis purus non blandit ultricies.Vestibulum vehicula massa vitae lacus facilisis, eget tristique nulla tristique.Mauris eleifend sit amet velit ut ultrices.Pellentesque laoreet est at felis mattis egestas.Curabitur sed nisl sed metus facilisis accumsan vitae eu eros.Nulla finibus, lacus porta finibus venenatis, elit lectus sollicitudin elit, a commodo nulla tellus nec dui.Vestibulum quis accumsan orci, et interdum orci.Nulla pharetra vehicula semper.Integer scelerisque at risus ut euismod.Nam quis dui maximus, imperdiet nisl a, dapibus odio.Etiam vehicula tortor vehicula purus fringilla, id cursus sem hendrerit.Sed ut lectus vel ex tempor scelerisque.',

'Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nullam semper urna et augue placerat, id lobortis ex mollis.Phasellus urna diam, fringilla a cursus a, ullamcorper vitae ipsum.Phasellus aliquam hendrerit ligula sit amet tempor.Nullam et ipsum efficitur, tristique ante vel, dignissim nisl.Phasellus luctus metus nec orci pharetra tristique ut eget ante.Donec arcu diam, porttitor ac facilisis non, efficitur eu magna.Etiam id malesuada nulla.Donec euismod ornare lectus.Nam ac nisi enim.Morbi laoreet diam lorem, quis convallis mi sagittis ut.Aenean viverra tellus eros, in pharetra elit finibus ac.Quisque dolor massa, tempus sit amet vulputate vitae, vulputate vitae enim.Sed condimentum et ex sed auctor.Curabitur dictum nec ipsum vel ullamcorper.',

'Nullam commodo ultricies purus vitae rutrum.Vivamus congue libero at mauris molestie iaculis.Pellentesque fringilla quam est, at fermentum nibh condimentum id.Morbi vestibulum iaculis dolor, ut vulputate purus interdum et.Fusce sit amet elementum tortor.Curabitur cursus quam quis odio pulvinar, consectetur aliquet libero aliquam.Etiam tempus luctus odio, et luctus ligula ultrices ut.Curabitur metus dui, condimentum at arcu sed, commodo accumsan tortor.Nullam a felis at est viverra condimentum et in odio.Nunc laoreet, erat ac tristique consequat, dolor dolor tempor leo, et condimentum orci lorem finibus purus.Ut hendrerit tempus tempor.Integer commodo nulla ac tincidunt gravida.Cras eget velit vitae lorem porta lobortis.Aliquam erat volutpat.',

'Donec id tellus vitae lacus bibendum elementum quis eget nisi.Etiam quis vestibulum magna.In nec commodo nisl.Etiam vel eros sollicitudin, pulvinar ipsum sit amet, rhoncus velit.Cras suscipit sem lorem, ac maximus lorem fermentum ornare.Sed porttitor ante sit amet sem finibus pulvinar.Sed convallis pretium lectus, eu hendrerit tellus euismod eu.Etiam vitae enim non augue vulputate fringilla.Pellentesque ultricies tellus eget commodo fermentum.',

]
export default para;